name: EcoBridgeUShopAdapter
version: 1.0.0
main: top.ellan.ecobridge.adapter.ushop.EcoBridgeUShopAdapter
# 按照您的要求，保持 1.21.11 版本定义
api-version: 1.21.11
author: Ellan
description: 应用 1.25x 买卖差价并对接 UltimateShop 的官方适配器。

# 强制依赖：如果缺少以下插件，本适配器将不会加载
# 同时保证了加载顺序：EcoBridge/UltimateShop -> EcoBridgeUShopAdapter
depend: 
  - EcoBridge
  - UltimateShop

# 如果您希望在未来添加手动重载命令，可以取消以下注释
# commands:
#   ecobridgeushop:
#     description: 适配器管理命令
#     usage: /<command> reload
#     permission: ecobridge.admin